spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848

    alicloud:
      access-key: LTAI5tC8XdAsMHLDL5nhMfq1
      secret-key: ZX66Fd1qL5DTWhk3PO3CRpcpPq1F5y
      oss:
        endpoint: oss-us-east-1.aliyuncs.com
        bucket: mall-rex

  application:
    name: mall-third-party

server:
  port: 30000